server:
  port: 9001

spring:
  application:
    name: ceo-service
  datasource:
    url: jdbc:mysql://localhost:3306/ceo?serverTimezone=Asia/Seoul
    username: root
    password: rlatnehd@123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeSerializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeSerializer
      group-id: ceo-group
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

  server:
    enable-self-preservation: false