server:
  port: 0

spring:
  application:
    name: pay-service
  datasource:
    url: jdbc:mysql://localhost:3306/pay?serverTimezone=Asia/Seoul
    username: root
    password: rlatnehd@123

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

  server:
    enable-self-preservation: false

# temp
jwt:
  secret: askjfnlsdkflkasdfkjdnfpsd1087734idjfnmapSdf123asdasd