server:
  port: 0

spring:
  application:
    name: order-command-service
  datasource:
    url: jdbc:h2:mem:test1
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
        hibernate:
            format_sql: true

  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

  server:
    enable-self-preservation: false